apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2019-10-12T16:58:16Z"
    name: admin
    namespace: uploader
    resourceVersion: "311810"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/uploader/rolebindings/admin
    uid: 7c06d0af-ed11-11e9-9152-0662d6531ac4
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: kube:admin
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/description: Allows deploymentconfigs in this namespace to rollout
        pods in this namespace.  It is auto-managed by a controller; remove subjects
        to disable.
    creationTimestamp: "2019-10-12T16:58:16Z"
    name: system:deployers
    namespace: uploader
    resourceVersion: "311802"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/uploader/rolebindings/system%3Adeployers
    uid: 7c04529e-ed11-11e9-9152-0662d6531ac4
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: uploader
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/description: Allows builds in this namespace to push images to
        this namespace.  It is auto-managed by a controller; remove subjects to disable.
    creationTimestamp: "2019-10-12T16:58:16Z"
    name: system:image-builders
    namespace: uploader
    resourceVersion: "311801"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/uploader/rolebindings/system%3Aimage-builders
    uid: 7c01f0d4-ed11-11e9-9152-0662d6531ac4
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
    namespace: uploader
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/description: Allows all pods in this namespace to pull images from
        this namespace.  It is auto-managed by a controller; remove subjects to disable.
    creationTimestamp: "2019-10-12T16:58:16Z"
    name: system:image-pullers
    namespace: uploader
    resourceVersion: "311797"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/uploader/rolebindings/system%3Aimage-pullers
    uid: 7bfb596a-ed11-11e9-9152-0662d6531ac4
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:image-puller
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:uploader
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
