apiVersion: v1
items:
- apiVersion: v1
  imagePullSecrets:
  - name: builder-dockercfg-jtj2h
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2019-10-12T16:58:16Z"
    name: builder
    namespace: uploader
    resourceVersion: "311815"
    selfLink: /api/v1/namespaces/uploader/serviceaccounts/builder
    uid: 7bfabc8a-ed11-11e9-884c-0ab5bf0f89de
  secrets:
  - name: builder-token-sg2xn
  - name: builder-dockercfg-jtj2h
- apiVersion: v1
  imagePullSecrets:
  - name: default-dockercfg-d2l22
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2019-10-12T16:58:16Z"
    name: default
    namespace: uploader
    resourceVersion: "311814"
    selfLink: /api/v1/namespaces/uploader/serviceaccounts/default
    uid: 7bfa9df5-ed11-11e9-884c-0ab5bf0f89de
  secrets:
  - name: default-token-6lfwx
  - name: default-dockercfg-d2l22
- apiVersion: v1
  imagePullSecrets:
  - name: deployer-dockercfg-qxjrv
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2019-10-12T16:58:16Z"
    name: deployer
    namespace: uploader
    resourceVersion: "311816"
    selfLink: /api/v1/namespaces/uploader/serviceaccounts/deployer
    uid: 7bfd1ad5-ed11-11e9-884c-0ab5bf0f89de
  secrets:
  - name: deployer-token-wz4gh
  - name: deployer-dockercfg-qxjrv
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
